In [1]:
import pandas as pd

In [2]:
filename = '../../Sample_Data/Raw/title.crew.tsv/data.tsv'
df = pd.read_csv(filename, sep='\t')
df.head()

tconst  directors writers
0  tt0000001  nm0005690      \N
1  tt0000002  nm0721526      \N
2  tt0000003  nm0721526      \N
3  tt0000004  nm0721526      \N
4  tt0000005  nm0005690      \N

In [3]:
filename = '../../Sample_Data/For_Modeling/roi.plot.genresplitted.tsv'
movie_data = pd.read_csv(filename, sep='\t')
movie_data.head()

tconst                                         name  date  prod_budget  \
0  tt4154796                            Avengers: Endgame  2019    400000000   
1  tt1298650  Pirates of the Caribbean: On Stranger Tides  2011    379000000   
2  tt2395427                      Avengers: Age of Ultron  2015    365000000   
3  tt4154756                       Avengers: Infinity War  2018    300000000   
4  tt0974015                               Justice League  2017    300000000   

   domestic_gross  worldwide_gross  isAdult startYear runtimeMinutes  Action  \
0       858373000       2797800564        0      2019            181       1   
1       241063875       1045663875        0      2011            136       1   
2       459005868       1403013963        0      2015            141       1   
3       678815482       2048359754        0      2018            149       1   
4       229024295        655945209        0      2017            120       1   

   ...  War  Biography  Western  Sport  Music  News  Film-Noir  ROI_domestic  \
0  ...    0          0        0      0      0     0          0      2.145932   
1  ...    0          0        0      0      0     0          0      0.636052   
2  ...    0          0        0      0      0     0          0      1.257550   
3  ...    0          0        0      0      0     0          0      2.262718   
4  ...    0          0        0      0      0     0          0      0.763414   

   ROI_worldwide                                               plot  
0       6.994501  In the opening, Clint Barton is teaching his d...  
1       2.759008  Captain Jack Sparrow (Johnny Depp) travels to ...  
2       3.843874  In the Eastern European country of Sokovia, th...  
3       6.827866  SPOILER: Thanos and his Children - Proxima Mid...  
4       2.186484  The film opens with camera phone footage of Cl...  

[5 rows x 36 columns]

In [4]:
movie_data_tconst_list = movie_data.tconst.values.tolist()

In [5]:
df_tconst_list = df.tconst.values.tolist()
# num = 0
# for tconst in df_tconst_list:
#     if tconst in movie_data_tconst_list:
#          num += 1
# print(num)

In [6]:
df = df.drop(df[~df['tconst'].isin(movie_data_tconst_list)].index)
len(df)

4617

In [7]:
df

tconst                                          directors  \
11392    tt0011549                                          nm0587754   
16399    tt0016641  nm0629243,nm0102643,nm0127511,nm0169905,nm0002271   
19449    tt0019729                                          nm0064600   
23633    tt0024034                                          nm0045800   
24141    tt0024548                                          nm0792514   
...            ...                                                ...   
6661883  tt9889072                                          nm8492670   
6663519  tt9892546                                          nm2648766   
6663587  tt9892692                                          nm0140498   
6666993  tt9899880                                          nm5971240   
6669990  tt9906218                                          nm0932216   

                                                   writers  
11392                                  nm0137414,nm0806061  
16399    nm0908753,nm0558923,nm0933133,nm0385012,nm0129721  
19449              nm0332539,nm0396876,nm0322299,nm0049898  
23633              nm0416861,nm0786827,nm0740622,nm0093456  
24141                        nm0922213,nm0857710,nm0109148  
...                                                    ...  
6661883                                nm8492670,nm8492674  
6663519                                         nm10168583  
6663587                                nm0140498,nm5609795  
6666993                                          nm5971240  
6669990                                                 \N  

[4617 rows x 3 columns]

In [8]:
df['persons'] = df['directors']+','+df['writers']
df

tconst                                          directors  \
11392    tt0011549                                          nm0587754   
16399    tt0016641  nm0629243,nm0102643,nm0127511,nm0169905,nm0002271   
19449    tt0019729                                          nm0064600   
23633    tt0024034                                          nm0045800   
24141    tt0024548                                          nm0792514   
...            ...                                                ...   
6661883  tt9889072                                          nm8492670   
6663519  tt9892546                                          nm2648766   
6663587  tt9892692                                          nm0140498   
6666993  tt9899880                                          nm5971240   
6669990  tt9906218                                          nm0932216   

                                                   writers  \
11392                                  nm0137414,nm0806061   
16399    nm0908753,nm0558923,nm0933133,nm0385012,nm0129721   
19449              nm0332539,nm0396876,nm0322299,nm0049898   
23633              nm0416861,nm0786827,nm0740622,nm0093456   
24141                        nm0922213,nm0857710,nm0109148   
...                                                    ...   
6661883                                nm8492670,nm8492674   
6663519                                         nm10168583   
6663587                                nm0140498,nm5609795   
6666993                                          nm5971240   
6669990                                                 \N   

                                                   persons  
11392                        nm0587754,nm0137414,nm0806061  
16399    nm0629243,nm0102643,nm0127511,nm0169905,nm0002...  
19449    nm0064600,nm0332539,nm0396876,nm0322299,nm0049898  
23633    nm0045800,nm0416861,nm0786827,nm0740622,nm0093456  
24141              nm0792514,nm0922213,nm0857710,nm0109148  
...                                                    ...  
6661883                      nm8492670,nm8492670,nm8492674  
6663519                               nm2648766,nm10168583  
6663587                      nm0140498,nm0140498,nm5609795  
6666993                                nm5971240,nm5971240  
6669990                                       nm0932216,\N  

[4617 rows x 4 columns]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['persons'].values.tolist())
print(vectorizer.get_feature_names())

['nm0000019', 'nm0000033', 'nm0000037', 'nm0000040', 'nm0000041', 'nm0000076', 'nm0000092', 'nm0000095', 'nm0000101', 'nm0000104', 'nm0000106', 'nm0000108', 'nm0000110', 'nm0000114', 'nm0000116', 'nm0000118', 'nm0000120', 'nm0000123', 'nm0000126', 'nm0000127', 'nm0000128', 'nm0000129', 'nm0000131', 'nm0000141', 'nm0000142', 'nm0000149', 'nm0000154', 'nm0000158', 'nm0000160', 'nm0000163', 'nm0000165', 'nm0000169', 'nm0000175', 'nm0000180', 'nm0000184', 'nm0000185', 'nm0000186', 'nm0000188', 'nm0000196', 'nm0000200', 'nm0000209', 'nm0000217', 'nm0000219', 'nm0000226', 'nm0000228', 'nm0000229', 'nm0000230', 'nm0000231', 'nm0000233', 'nm0000241', 'nm0000243', 'nm0000246', 'nm0000247', 'nm0000251', 'nm0000255', 'nm0000264', 'nm0000265', 'nm0000269', 'nm0000277', 'nm0000316', 'nm0000318', 'nm0000329', 'nm0000335', 'nm0000338', 'nm0000339', 'nm0000341', 'nm0000343', 'nm0000345', 'nm0000354', 'nm0000361', 'nm0000362', 'nm0000365', 'nm0000367', 'nm0000382', 'nm0000386', 'nm0000390', 'nm0000399'

In [10]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
def set_value(row_number, assigned_value): 
    if row_number in assigned_value:
        return assigned_value[row_number]
    else:
        return None

In [12]:
roi_domestic_list = movie_data.loc[:, ['tconst', 'ROI_domestic']].values.tolist()

In [13]:
roi_domestic_dict = {}
for i in roi_domestic_list:
    roi_domestic_dict[i[0]] = i[1]

In [14]:
df['ROI_domestic'] = df['tconst'].apply(set_value, args =(roi_domestic_dict, ))

In [15]:
df

tconst                                          directors  \
11392    tt0011549                                          nm0587754   
16399    tt0016641  nm0629243,nm0102643,nm0127511,nm0169905,nm0002271   
19449    tt0019729                                          nm0064600   
23633    tt0024034                                          nm0045800   
24141    tt0024548                                          nm0792514   
...            ...                                                ...   
6661883  tt9889072                                          nm8492670   
6663519  tt9892546                                          nm2648766   
6663587  tt9892692                                          nm0140498   
6666993  tt9899880                                          nm5971240   
6669990  tt9906218                                          nm0932216   

                                                   writers  \
11392                                  nm0137414,nm0806061   
16399    nm0908753,nm0558923,nm0933133,nm0385012,nm0129721   
19449              nm0332539,nm0396876,nm0322299,nm0049898   
23633              nm0416861,nm0786827,nm0740622,nm0093456   
24141                        nm0922213,nm0857710,nm0109148   
...                                                    ...   
6661883                                nm8492670,nm8492674   
6663519                                         nm10168583   
6663587                                nm0140498,nm5609795   
6666993                                          nm5971240   
6669990                                                 \N   

                                                   persons  ROI_domestic  
11392                        nm0587754,nm0137414,nm0806061     30.000000  
16399    nm0629243,nm0102643,nm0127511,nm0169905,nm0002...      2.307692  
19449    nm0064600,nm0332539,nm0396876,nm0322299,nm0049898      7.387863  
23633    nm0045800,nm0416861,nm0786827,nm0740622,nm0093456      3.275626  
24141              nm0792514,nm0922213,nm0857710,nm0109148     10.000000  
...                                                    ...           ...  
6661883                      nm8492670,nm8492670,nm8492674      0.091381  
6663519                               nm2648766,nm10168583      7.762508  
6663587                      nm0140498,nm0140498,nm5609795      0.078029  
6666993                                nm5971240,nm5971240      1.453010  
6669990                                       nm0932216,\N      0.858557  

[4617 rows x 5 columns]

In [16]:
df.to_csv('../../Sample_Data/Processed/movie.crews.combined.tsv', sep='\t', index=False)

In [17]:
X.shape

(4617, 7711)

In [18]:
import numpy as np
persons_lists = df.persons.values.tolist()
persons_lists = [persons.split(',') for persons in persons_lists]
v = persons_lists
l = [len(x) for x in v]
f, u = pd.factorize(np.concatenate(v))
n, m = len(v), u.size
i = np.arange(n).repeat(l)

dummies = pd.DataFrame(
    np.bincount(i * m + f, minlength=n * m).reshape(n, m),
    df.index, u
)

df = df.drop('persons', 1).join(dummies)

In [19]:
df

tconst                                          directors  \
11392    tt0011549                                          nm0587754   
16399    tt0016641  nm0629243,nm0102643,nm0127511,nm0169905,nm0002271   
19449    tt0019729                                          nm0064600   
23633    tt0024034                                          nm0045800   
24141    tt0024548                                          nm0792514   
...            ...                                                ...   
6661883  tt9889072                                          nm8492670   
6663519  tt9892546                                          nm2648766   
6663587  tt9892692                                          nm0140498   
6666993  tt9899880                                          nm5971240   
6669990  tt9906218                                          nm0932216   

                                                   writers  ROI_domestic  \
11392                                  nm0137414,nm0806061     30.000000   
16399    nm0908753,nm0558923,nm0933133,nm0385012,nm0129721      2.307692   
19449              nm0332539,nm0396876,nm0322299,nm0049898      7.387863   
23633              nm0416861,nm0786827,nm0740622,nm0093456      3.275626   
24141                        nm0922213,nm0857710,nm0109148     10.000000   
...                                                    ...           ...   
6661883                                nm8492670,nm8492674      0.091381   
6663519                                         nm10168583      7.762508   
6663587                                nm0140498,nm5609795      0.078029   
6666993                                          nm5971240      1.453010   
6669990                                                 \N      0.858557   

         nm0587754  nm0137414  nm0806061  nm0629243  nm0102643  nm0127511  \
11392            1          1          1          0          0          0   
16399            0          0          0          1          1          1   
19449            0          0          0          0          0          0   
23633            0          0          0          0          0          0   
24141            0          0          0          0          0          0   
...            ...        ...        ...        ...        ...        ...   
6661883          0          0          0          0          0          0   
6663519          0          0          0          0          0          0   
6663587          0          0          0          0          0          0   
6666993          0          0          0          0          0          0   
6669990          0          0          0          0          0          0   

         ...  nm2404468  nm3469867  nm8681607  nm10525589  nm8492670  \
11392    ...          0          0          0           0          0   
16399    ...          0          0          0           0          0   
19449    ...          0          0          0           0          0   
23633    ...          0          0          0           0          0   
24141    ...          0          0          0           0          0   
...      ...        ...        ...        ...         ...        ...   
6661883  ...          0          0          0           0          2   
6663519  ...          0          0          0           0          0   
6663587  ...          0          0          0           0          0   
6666993  ...          0          0          0           0          0   
6669990  ...          0          0          0           0          0   

         nm8492674  nm10168583  nm0140498  nm5971240  nm0932216  
11392            0           0          0          0          0  
16399            0           0          0          0          0  
19449            0           0          0          0          0  
23633            0           0          0          0          0  
24141            0           0          0          0          0  
...            ...         ...      

In [20]:
person_average_roi = {}
for person in vectorizer.get_feature_names():
    person_average_roi[person] = df[df[person]!=0]['ROI_domestic'].mean()

In [21]:
person_average_roi

{'nm0000019': 0.4,
 'nm0000033': 4.016666666666666,
 'nm0000037': 2.8346456692913384,
 'nm0000040': 2.88679301148413,
 'nm0000041': 1.18193164,
 'nm0000076': 0.017371875,
 'nm0000092': 4.977836388888888,
 'nm0000095': 1.2701804863360397,
 'nm0000101': 5.096687227777778,
 'nm0000104': 0.13028013333333333,
 'nm0000106': 0.8718122666666667,
 'nm0000108': 1.2417243166727063,
 'nm0000110': 1.3562651878787877,
 'nm0000114': 0.44254892307692306,
 'nm0000116': 2.0830875269588143,
 'nm0000118': 19.547559438527582,
 'nm0000120': 6.0181163333333325,
 'nm0000123': 0.9971593522702935,
 'nm0000126': 5.969355989878543,
 'nm0000127': 6.041677589885234,
 'nm0000128': 0.18667186666666666,
 'nm0000129': 1.37784555,
 'nm0000131': 1.0980764722222223,
 'nm0000141': 0.194266,
 'nm0000142': 2.150714227002354,
 'nm0000149': 0.8128798080246913,
 'nm0000154': 3.783474509444445,
 'nm0000158': 5.76495395,
 'nm0000160': 2.7999756666666666,
 'nm0000163': 1.6716688181818182,
 'nm0000165': 1.1105531280168492,
 'nm0000

In [22]:
df.to_csv('../../Sample_Data/Processed/movie.crewsplitted.tsv', sep='\t', index=False)

In [23]:
with open('../../Sample_Data/For_Modeling/person.averageroi.tsv', 'w') as f:
    f.write('personid\taverageroi\n')
    for key in person_average_roi:
        f.write('{}\t{}\n'.format(key, person_average_roi[key]))